/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller_input_test;

import org.junit.Test;
import static org.junit.Assert.*;

public class ControllerInputTestTest {

}
